### ISSUE TITLE
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by idf** [grangier/python-goose#78]
I am using Goose on Windows Platform. 

Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.

> > > from goose import Goose
> > > Goose()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "d:\Program Files (x86)\python273\lib\site-packages\goose_extractor-1.0.8
> > > -py2.7.egg\goose__init__.py", line 38, in **init**
> > >     self.initialize()
> > >   File "d:\Program Files (x86)\python273\lib\site-packages\goose_extractor-1.0.8
> > > -py2.7.egg\goose__init__.py", line 82, in initialize
> > >     os.remove(path)
> > > WindowsError: [Error 32] The process cannot access the file because it is being
> > > used by another process: 'c:\users\danyang\appdata\local\temp\goose\tmpj2
> > > avys'

**Comment by jerwin2018** [comment]
ERROR: Could not install packages due to an EnvironmentError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-req-tracker-d0sxobbf\\57c162bad943c226c1d2a75e59537b7845202d095bf28c0bcc570868'
Consider using the `--user` option or check the permissions.
